"""upgrading  schema sync

Revision ID: 327bc84bedeb
Revises: 282ba3e603cc
Create Date: 2026-05-05 12:16:09.270042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '327bc84bedeb'
down_revision: Union[str, None] = '282ba3e603cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
