"""upgrading  schema sync

Revision ID: 3a7809baad5f
Revises: e1c1d75dbefe
Create Date: 2026-05-05 13:42:26.151027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a7809baad5f'
down_revision: Union[str, None] = 'e1c1d75dbefe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_name')
    # ### end Alembic commands ###
