"""upgrading  schema sync

Revision ID: 97a8b18b64f2
Revises: d82fd6de5dc1
Create Date: 2026-05-06 13:23:14.210253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97a8b18b64f2'
down_revision: Union[str, None] = 'd82fd6de5dc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
