"""upgrading  schema sync

Revision ID: b3be1f4a0857
Revises: f8a2c1d4e5b6
Create Date: 2026-05-06 12:52:25.449470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3be1f4a0857'
down_revision: Union[str, None] = 'f8a2c1d4e5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_constraint(op.f('orders_customer_id_fkey'), 'orders', type_='foreignkey')
    op.drop_column('orders', 'customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('orders_customer_id_fkey'), 'orders', 'users', ['customer_id'], ['id'])
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    # ### end Alembic commands ###
