"""initial schema sync

Revision ID: d59865d3a6bd
Revises: 
Create Date: 2026-05-05 11:44:29.490889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd59865d3a6bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_contact', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('stripe_session_id', sa.String(), nullable=True))
    op.alter_column('orders', 'reschedule_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.alter_column('orders', 'reschedule_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('orders', 'stripe_session_id')
    op.drop_column('orders', 'customer_contact')
    # ### end Alembic commands ###
