"""upgrading  schema sync

Revision ID: d82fd6de5dc1
Revises: b3be1f4a0857
Create Date: 2026-05-06 13:21:55.172274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd82fd6de5dc1'
down_revision: Union[str, None] = 'b3be1f4a0857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
